const productData = [
  {
    id: 0,
    img: "/images/product__1.webp",
    name: "Monochromatic Multi Stick",
    price: 41.0,
    category: ["lipsticks"],
    sale: false,
  },
  {
    id: 1,
    img: "/images/product__2.jpg",
    name: "Monochromatic Multi Stick",
    price: 41.0,
    category: ["lipsticks"],
    sale: false,
  },
  {
    id: 2,
    img: "/images/product__3.jpg",
    name: "Monochromatic Multi Stick",
    price: 41.0,
    category: ["lipsticks"],
    sale: false,
  },
  {
    id: 3,
    img: "/images/product__4.webp",
    name: "Better Lotion",
    price: 31.0,
    category: ["skin care"],
    sale: false,
  },
  {
    id: 4,
    img: "/images/product__5.webp",
    name: "Better Lotion",
    price: 31.0,
    category: ["skin care"],
    sale: false,
  },
  {
    id: 5,
    img: "/images/product__6.webp",
    name: "Better Lotion",
    price: 31.0,
    category: ["skin care"],
    sale: false,
  },
  {
    id: 6,
    img: "/images/product__7.webp",
    name: "Koccido Makeup",
    price: 51.0,
    category: ["makeup"],
    sale: false,
  },
  {
    id: 7,
    img: "/images/product__8.webp",
    name: "Koccido Makeup",
    price: 51.0,
    category: ["makeup"],
    sale: false,
  },
  {
    id: 8,
    img: "/images/product__9.webp",
    name: "Koccido Makeup",
    price: 51.0,
    category: ["makeup"],
    sale: false,
  },
  {
    id: 9,
    img: "/images/product__6.webp",
    name: "Double Beauty",
    price: 51.0,
    category: ["makeup", "lipsticks"],
    sale: false,
  },
  {
    id: 10,
    img: "/images/product__7.webp",
    name: "Double Beauty",
    price: 51.0,
    category: ["makeup", "lipsticks"],
    sale: false,
  },
  {
    id: 11,
    img: "/images/product__8.webp",
    name: "Double Beauty",
    price: 51.0,
    category: ["makeup", "lipsticks"],
    sale: false,
  },
  {
    id: 12,
    img: "/images/product__10.webp",
    name: "Karite",
    price: 41.0,
    category: ["nail & wax"],
    sale: true,
  },
  {
    id: 13,
    img: "/images/product__11.webp",
    name: "Karite",
    price: 41.0,
    category: ["nail & wax"],
    sale: true,
  },
  {
    id: 14,
    img: "/images/product__12.jpg",
    name: "Karite",
    price: 41.0,
    category: ["nail & wax"],
    sale: true,
  },
  {
    id: 15,
    img: "/images/product__1.webp",
    name: "Karite Dior",
    price: 71.0,
    category: ["makeup", "nail & wax"],
    sale: true,
  },
  {
    id: 16,
    img: "/images/product__2.jpg",
    name: "Karite Dior",
    price: 71.0,
    category: ["makeup", "nail & wax"],
    sale: true,
  },
  {
    id: 17,
    img: "/images/product__12.jpg",
    name: "Karite Dior",
    price: 71.0,
    category: ["makeup", "nail & wax"],
    sale: true,
  },
  {
    id: 18,
    img: "/images/product__10.webp",
    name: "Karite Dior",
    price: 71.0,
    category: ["makeup", "nail & wax"],
    sale: true,
  },
  {
    id: 19,
    img: "/images/product__11.webp",
    name: "Karite Dior",
    price: 71.0,
    category: ["makeup", "nail & wax"],
    sale: true,
  },
  {
    id: 20,
    img: "/images/product__12.jpg",
    name: "Karite Dior",
    price: 71.0,
    category: ["makeup", "nail & wax"],
    sale: true,
  },
  {
    id: 21,
    img: "/images/product__13.webp",
    name: "Teenitor",
    price: 37.0,
    category: ["nail & wax"],
    sale: false,
  },
  {
    id: 22,
    img: "/images/product__14.webp",
    name: "Teenitor",
    price: 37.0,
    category: ["nail & wax"],
    sale: false,
  },
  {
    id: 23,
    img: "/images/product__15.webp",
    name: "Teenitor",
    price: 37.0,
    category: ["nail & wax"],
    sale: false,
  },
  {
    id: 24,
    img: "/images/product__16.webp",
    name: "Manna Kadar Beauty",
    price: 27.0,
    category: ["makeup"],
    sale: true,
  },
  {
    id: 25,
    img: "/images/product__17.webp",
    name: "Manna Kadar Beauty",
    price: 27.0,
    category: ["makeup"],
    sale: true,
  },
  {
    id: 26,
    img: "/images/product__18.webp",
    name: "Manna Kadar Beauty",
    price: 27.0,
    category: ["makeup"],
    sale: true,
  },
  {
    id: 27,
    img: "/images/product__19.webp",
    name: "Skin Renewing",
    price: 27.0,
    category: ["skin care"],
    sale: true,
  },
  {
    id: 28,
    img: "/images/product__20.webp",
    name: "Skin Renewing",
    price: 27.0,
    category: ["skin care"],
    sale: true,
  },
  {
    id: 29,
    img: "/images/product__21.webp",
    name: "Skin Renewing",
    price: 27.0,
    category: ["skin care"],
    sale: true,
  },
  {
    id: 30,
    img: "/images/product__22.webp",
    name: "Wild Mega High-Shine",
    price: 19.0,
    category: ["lipsticks"],
    sale: true,
  },
  {
    id: 31,
    img: "/images/product__23.webp",
    name: "Wild Mega High-Shine",
    price: 19.0,
    category: ["lipsticks"],
    sale: true,
  },
  {
    id: 32,
    img: "/images/product__24.webp",
    name: "Wild Mega High-Shine",
    price: 19.0,
    category: ["lipsticks"],
    sale: true,
  },
  {
    id: 33,
    img: "/images/product__25.webp",
    name: "Wild Mega High-Shine",
    price: 19.0,
    category: ["lipsticks"],
    sale: true,
  },
];

export default productData;